[package]
name = "practice001"
version = "0.1.0"
authors = ["Derick Chou <derick.chou@fluxconn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
